### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by menghuaa** [GitGyun/visual_token_matching#1]
Hello, how much memory is required during training and how long does it take to train?

**Comment by menghuaa** [comment]
> With our default setting, the training takes about 100G memory (25 x 4) and 2~3 days with four A6000 GPUs.

@GitGyun Hello, don't I need to download  data of edge_occlusion、edge_texture?

**Comment by GitGyun** [comment]
You need to download "edge_occlusion" (I didn't put in the instruction by mistake, and I've updated the instruction.)
You don't need to download "edge_texture" because we use our own SobelEdgeDetector.
