### ISSUE TITLE
Inquiry about Dataset Composition

### ISSUE THREAD

**Issue by JH-GEECS** [GitGyun/visual_token_matching#9]
Thank you very much for sharing your excellent algorithm and research paper. However, I have a question that I would like to inquire about during the learning process, so I am leaving an issue.

Regarding Taskonomy tiny, it is composed of 35 scenes for the train and validation split. While analyzing the omnidata_tools/dataset/starter_dataset/component_datasets/taskonomy/init.py file of the library during the download using omnidownloader, I noticed that woodbine is excluded from the train split, as indicated by the line: "forbidden_buildings = ['mosquito', 'tansboro', 'tomkins', 'darnestown', 'brinnon', 'rough', 'woodbine'] # We do not have the rgb data for tomkins, darnestown, brinnon". I also confirmed that woodbine is indeed excluded during the actual download.

Therefore, I believe that only 34 scenes were used in the training of the model. I wanted to inquire if this is indeed the case and if there might be a slight discrepancy in reproducing the research described in the paper.

Thank you very much.

Sincerely,
Jiho Choi

**Comment by ijihoon98** [comment]
I've had the same problem as you. To solve this, 'woodbine' data was downloaded directly through `wget`. See the link below.

https://datasets.epfl.ch/taskonomy/links.txt

**Comment by rajayarli** [comment]
@ijihoon98 could be please be elloborate with this:
About the building info what exactly are we using? when i downloaded the tiny dataset i can see the taskonomy folder consisting of 
![image](https://github.com/GitGyun/visual_token_matching/assets/62141897/2321d96d-e6eb-4e84-b2cc-1cc4e76dd883)
but in the building train list I cant find the name of ackermanville.
![image](https://github.com/GitGyun/visual_token_matching/assets/62141897/def99a0d-5aab-4aa4-9477-83bb1c5ee35b)

![d2](https://github.com/GitGyun/visual_token_matching/assets/62141897/14d6ca89-962e-4743-8197-9054be510868)
you said that downloading the woodbine will solve that, but I which woodbine file were you talking about?
![image](https://github.com/GitGyun/visual_token_matching/assets/62141897/de507e27-2fc7-45e3-adb0-b62066506542)
I tried to download the RGB file of woodbine and replaced the RGB folder of tiny dataset still getting this error:




python main.py --stage 0 --task_fold 1
C:\Users\rajar\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\amp\autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Load ckpt from model/pretrained_checkpoints\beit_base_patch16_224_pt22k.pth
Load state_dict by model_key = model
Expand the shared relative position embedding to each transformer block.
Traceback (most recent call last):
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\main.py", line 75, in <module>
    run(config)
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\main.py", line 25, in run
    model, ckpt_path = load_model(config, verbose=IS_RANK_ZERO)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\train\train_utils.py", line 228, in load_model
    model = LightningTrainWrapper(config, verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\train\trainer.py", line 37, in __init__
    self.support_data = self.load_support_data()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\train\trainer.py", line 52, in load_support_data
    support_data = generate_support_data(self.config, data_path=data_path, verbose=self.verbose)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\dataset\dataloader_factory.py", line 218, in generate_support_data
    dset = TaskonomySegmentationDataset(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\dataset\taskonomy.py", line 550, in __init__
    self.class_idxs = [class_idx for class_idx in class_idxs if self.img_paths[class_idx].split('_')[0] in buildings]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\dataset\taskonomy.py", line 550, in <listcomp>
    self.class_idxs = [class_idx for class_idx in class_idxs if self.img_paths[class_idx].split('_')[0] in buildings]
                                                                ~~~~~~~~~~~~~~^^^^^^^^^^^

**Comment by ijihoon98** [comment]
@rajayarli Please change the code line <self.class_idxs = [class_idx for class_idx in class_idxs if self.img_paths[class_idx].split('')[0] in buildings] >
to <self.class_idxs = [class_idx for class_idx in class_idxs if class_idx<len(self.img_paths) and self.img_paths[class_idx].split('')[0] in buildings]>

**Comment by rajayarli** [comment]
> @rajayarli Please change the code line <self.class_idxs = [class_idx for class_idx in class_idxs if self.img_paths[class_idx].split('')[0] in buildings] > to <self.class_idxs = [class_idx for class_idx in class_idxs if class_idx<len(self.img_paths) and self.img_paths[class_idx].split('')[0] in buildings]>

done that getting this error:
PS D:\OneDrive - Deakin University\Desktop\visual_token_matching> python main.py --stage 0 --task_fold 1
C:\Users\rajar\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\amp\autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Load ckpt from model/pretrained_checkpoints\beit_base_patch16_224_pt22k.pth
Load state_dict by model_key = model
Expand the shared relative position embedding to each transformer block.
Traceback (most recent call last):
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\main.py", line 75, in <module>
    run(config)
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\main.py", line 25, in run
    model, ckpt_path = load_model(config, verbose=IS_RANK_ZERO)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\train\train_utils.py", line 228, in load_model
    model = LightningTrainWrapper(config, verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\train\trainer.py", line 37, in __init__
    self.support_data = self.load_support_data()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\train\trainer.py", line 52, in load_support_data
    support_data = generate_support_data(self.config, data_path=data_path, verbose=self.verbose)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive - Deakin University\Desktop\visual_token_matching\dataset\dataloader_factory.py", line 227, in generate_support_data
    X, Y, M = batch
              ^^^^^
UnboundLocalError: cannot access local variable 'batch' where it is not associated with a value
